### ISSUE TITLE
OnDateSetListener does not pass Calendar corrected for minute interval

### ISSUE THREAD

**Issue by nickdaugherty** [bendemboski/DateSlider#9] opened 2012-05-15 17:11 UTC
When implementing an `OnDateSetListener` for a DateSlider, the `Calendar` object that is passed to the listener's `onDateSet` method is not adjusted to the configured `MINUTEINTERVAL`. Instead, the normal date is returned, so you end up getting dates in between the interval, such as 5:10 when the `MINUTEINTERVAL` is set to 15.

Expected behavior is the `Calendar` returned matches the date chosen by the user, without having to do a 

```
selectedDate.set(Calendar.MINUTE, selectedDate.get(Calendar.MINUTE)/TimeLabeler.MINUTEINTERVAL*TimeLabeler.MINUTEINTERVAL);
```

to correct it.

**Comment by bendemboski** [comment] 2012-05-15 17:53
This is a duplicate of #4

**Closed as completed by bendemboski** 2012-05-15 17:53 UTC
